# Site settings
title: Bobby Sparks
email: bsparks@stanford.edu
description: >
  Personal Website for Bobby Sparks
url: https://rbzsparks.githhub.io
repository: rbzsparks/rbzsparks.github.io
github_username:  rbzsparks
twitter_username: rbzsparks

gems: ['jekyll/scholar']

# Build settings
markdown: kramdown

max_year: 2022 #the most recent year with papers published
# i should figure out how to automate that...

exclude:
  - "files"
  - "wikiuploads"
  - "ignore"

exclude: [vendor]

keep_files:
  - "files"
  - "wikiuploads"

assets:
  sources:
    - assets/fonts

# for BibTeX
scholar:
  style: apa
  locale: en

  sort_by: year
  order: descending

  bibliography_list_tag: ul

  source: ./_bibliography
  bibliography: citations
  bibliography_template: <p>{{reference}} {{entry.annote}}</p>

  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   "[Abstract/BibTeX]"

  query: "@*"

